from __future__ import annotations

from typing import Protocol


class ProtocolAdapter(Protocol):
    name: str
    display_name: str

    def create_project_metadata(self) -> dict[str, str]: ...
    def load_doc_inputs(self, project_root: str) -> list[str]: ...
    def load_trace_inputs(self, project_root: str) -> list[str]: ...
    def load_seed_inputs(self, project_root: str) -> list[str]: ...

    def spec_system_prompt(self) -> str: ...
    def build_spec_user_message(self, docs_text: str, traces: list) -> str: ...

    def trace_system_prompt(self) -> str: ...
    def build_trace_user_message(self, all_sessions: list[list[dict]], all_events: list[dict], mt_result: dict, heuristic_states: list[dict]) -> str: ...

    def probe_system_prompt(self) -> str: ...

    def parse_session(self, raw_text: str) -> list[dict]: ...
    def parse_session_pairs(self, raw_text: str) -> list[dict]: ...
    def parse_trace(self, raw_text: str) -> list[dict]: ...

    def format_trace_summary(self, traces: list) -> str: ...
    def summarize_observed_messages(self, traces: list) -> str: ...

    def infer_candidate_states(self, sessions: list[list[dict]]) -> dict: ...
    def propose_transitions(self, states: list[dict], messages: list[dict]) -> dict: ...
    def normalize_transition(self, from_state: str, to_state: str, message_type: str) -> tuple[str, str, str]: ...
    def trace_augmentation_min_transitions(self) -> int: ...
    def trace_augmentation_priority_messages(self) -> list[str]: ...

    def select_probe_targets(self, transitions: list, invariants: list) -> list[dict]: ...
    def generate_probe_commands(self, target: dict) -> list[str]: ...
    def probe_target_host(self) -> str: ...
    def probe_target_port(self) -> int: ...
    def execute_probe(self, commands: list[str]) -> list[dict]: ...
